### ISSUE TITLE
Where am I supposed to paste the yaml for the Binary Power Up In Progress Sensor?

### ISSUE THREAD

**Issue by smurfyfp** [8none1/octopus_powerups#4]
The only place I know to put this kind of thing is in configuration.yaml, but it's not letting me put it there because there's no platform defined.

**Comment by 8none1** [comment]
It needs to go in a `template:` section as a `binary-sensor`.

So the full path would be something like:

```
template:
  ...
  - binary_sensor:
    - name: "Power Up In Progress"
    ...
```
