### ISSUE TITLE
Gmail API scopes?

### ISSUE THREAD

**Issue by BobC76** [8none1/octopus_powerups#5]
This is great, thanks for sharing. I wanted to host my own and modify for some other similar email notifications - e.g. local water company has a notification service for works near a location. By default when I tried running it asks for full access not just read only. Do you happen to know or can suggest the list of specific oauth scopes are needed to restrict it as much as possible? I assumed https://developers.google.com/gmail/api/auth/scopes would be self evident but the documentation isn't so helpful!

**Comment by BobC76** [comment]
Update: discovered that the problem was running the script within my "normal" google account and trying to give access to another "forwarding" account was the problem, despite setting up the auth scope

>   "oauthScopes": [
>     "https://www.googleapis.com/auth/gmail.readonly"
>   ]  

there's some other hidden blocker on using another account even though it appears possible when you're taken through the verification step.. Makes sense but didn't occur to me - got the following:

> Warning	This project requires access to your Google Account to run. Please try again and allow it this time.

But works fine if the script is run within the forwarding google account.

**Comment by 8none1** [comment]
> there's some other hidden blocker on using another account even though it appears possible when you're taken through the verification step..

My guess would be that your "normal" Google account is a "Workspace" account or ex-Google Apps For Domains one or something like that.  Or, perhaps you have whatever Google calls their enhanced security switched on. 

I had problems with both of these things and gave up and used a vanilla Google account.

Glad you got it working!  Closing as fixed, but please reopen or open a new issue if you have more problems.  Patches, especially docs, are welcome!  ;)
