### ISSUE TITLE
Power up event not clearing after the event

### ISSUE THREAD

**Issue by gcoan** [8none1/octopus_powerups#9]
no biggie but I noticed that yesterday's Octopus power up event is still showing in my REST sensor.  it normally clears an hour or so after the event.

Checking the REST URL, it's still reporting the same values so must be a problem at your end, not mine in polling it incorrectly.

![image](https://github.com/user-attachments/assets/27cb6cae-1500-498f-9e4e-8ceb56c44c16)

The sensor is proving to be super-useful, I've got an automation notification that tells me when there's a new event, then scripts to decode the date & times and to write those into Predbat to automatically take account of in my battery planning.

Cheers

**Comment by 8none1** [comment]
I bet this is because of the changes made to stop it uploading and empty file.  I think I know what to do...

**Comment by 8none1** [comment]
... no, it was even easier.  

I hadn't sync'd the README changes so it was refusing to upload.  Fixed.

**Comment by gcoan** [comment]
> ... no, it was even easier.  
> 
> I hadn't sync'd the README changes so it was refusing to upload.  Fixed.

Ha !

Thanks, I see the sensor has cleared now.

Cheers
